services:

  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8080:8080"
    depends_on: 
      - db
      - db-init
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: 'crm'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: 'crm'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  db-init:
    image: mysql:5.7
    depends_on:
      - db
    entrypoint: >
      sh -c "
      sleep 10 &&
      mysql -h db -u user -ppassword crm < /crm.session.sql
      "
    volumes:
      - ./crm.session.sql:/crm.session.sql
volumes:
  my-db: